### ISSUE TITLE
New release to-do

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Facebook-Messenger-Desktop#444]
- [x] Create a draft release on GitHub
- [x] Update branch `website`
- [ ] Ensure the update process works (to and from the new release)
- [ ] Publish to master (so users can update)
- [ ] Publish the website (branch `gh-pages`)

*let me do the last 2*

**Comment by Sytten** [comment]
As said I plan to do the beta first, so when you are done with the dmg I think we can publish it...

**Comment by Sytten** [comment]
Dont think its relevant anymore, see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
